image: java:8

stages:
    - build
    - acceptance-unit-test
    - acceptance-docker-build
    - acceptance-integration-test
    - release

build-ods:
    stage: build
    script: "./gradlew clean build -x test"
    after_script:
        - "./gradlew copyDockerAssets" # copy it for docker task
    artifacts:
        paths:
            - "./docker/ods/" # hand it to docker task

unit-tests-ods:
    stage: acceptance-unit-test
    script: "./gradlew test"
    artifacts:
        reports:
            junit: '*/build/test-results/**/*.xml'

docker-build-ods:
    image: docker:stable
    services:
        - docker:dind
    stage: acceptance-docker-build
    script: "docker build -t osrg_ods_public/ods-cd:latest ./docker/ods"
    dependencies: # copying is done by build-ods task
        - build-ods

docker-compose-ods:
    image: docker:stable
    services:
        - docker:dind
    stage: acceptance-integration-test
    script: "docker-compose -f docker/docker-compose.yml -f docker/docker-compose.local.yml up -d"

integration-tests-ods:
    stage: acceptance-integration-test
    script: "./gradlew integrationTest"

#docker-push-ods:
#    stage: release
#    script: "./gradlew dockerPush"

after_script:
    - "docker-compose -f docker/docker-compose.yml -f docker/docker-compose.local.yml stop"
