image: docker:stable
services:
    - docker:dind

# For predefined environment variables see: https://docs.gitlab.com/ee/ci/variables/
variables:
    # Instruct Testcontainers to use the daemon of DinD.
    # See further: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
    DOCKER_HOST: "tcp://docker:2375"
    # Improve performance with overlayfs.
    # See further: https://docs.docker.com/storage/storagedriver/overlayfs-driver/
    # See further: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
    DOCKER_DRIVER: "overlay2"
    IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}"

stages:
    - build
    - acceptance-unit-test
    - acceptance-docker-build
    - acceptance-integration-test
    - release

build-ods:
    image: java:8
    stage: build
    script: "./gradlew clean build -x test"
    after_script:
        - "./gradlew copyDockerAssets" # copy it for docker task
    artifacts:
        paths:
            - "./docker/ods/" # hand it to docker task

unit-tests-ods:
    image: java:8
    stage: acceptance-unit-test
    script: "./gradlew test"
    artifacts:
        reports:
            junit: '*/build/test-results/**/*.xml'

docker-build-ods:
    stage: acceptance-docker-build
    script: "docker build -t osrg_ods_public/ods-cd:latest ./docker/ods"
    dependencies: # copying is done by build-ods task
        - build-ods

integration-test:
    stage: acceptance-integration-test
    script:
        - "apk add curl"
        - "curl -L \"https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"
        - "chmod +x /usr/local/bin/docker-compose"
        - "docker-compose -f docker/docker-compose.yml -f docker/docker-compose.local.yml up -d"
        - "./gradlew integrationTest"
        - "docker-compose -f docker/docker-compose.yml -f docker/docker-compose.local.yml stop"

#docker-push-ods:
#    stage: release
#    script: "./gradlew dockerPush"