image: docker:stable
services:
    - docker:dind

# For predefined environment variables see: https://docs.gitlab.com/ee/ci/variables/
variables:
    # Instruct Testcontainers to use the daemon of DinD.
    # See further: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
    DOCKER_HOST: "tcp://docker:2375"
    # Improve performance with overlayfs.
    # See further: https://docs.docker.com/storage/storagedriver/overlayfs-driver/
    # See further: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
    DOCKER_DRIVER: "overlay2"
    IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}"
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

stages:
    - build
    - acceptance-unit-test
    - acceptance-docker-build
    - acceptance-integration-test
    - release

build:
    image: java:8
    stage: build
    script: "./gradlew clean build -x test"
    after_script:
        - "./gradlew copyDockerAssets" # copy it for docker task
    artifacts:
        paths:
            - "./docker/ods/" # hand it to docker task

unit-tests:
    image: java:8
    stage: acceptance-unit-test
    script: "./gradlew test"
    artifacts:
        reports:
            junit: "*/build/test-results/**/*.xml"

docker-build:
    stage: acceptance-docker-build
    script:
        - docker build -t registry.gitlab.com/profoss/open-data-service-legacy/open-data-service ./docker/ods
        - mkdir image
        - docker save registry.gitlab.com/profoss/open-data-service-legacy/open-data-service > image/ods.tar
    artifacts:
        paths:
            - image
    dependencies: # copying is done by build-ods task
        - build

integration-test:
    stage: acceptance-integration-test
    dependencies:
        - docker-build
    image:
        - http://registry.gitlab.com/profoss/open-data-service-legacy/ci-container
    script:
        - docker load -i image/ods.tar
        - docker-compose -f docker/docker-compose.yml -f docker/docker-compose.local.yml up -d
        - ./gradlew integrationTest
        - docker-compose docker-compose -f docker/docker-compose.yml -f docker/docker-compose.local.yml stop
# publish:
#     stage: release
#     dependencies:
#        - docker-build
#     script:
#        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#        - docker load -i image/ods.tar
#        - docker push registry.gitlab.com/profoss/open-data-service-legacy/open-data-service

#docker-push-ods:
#    stage: release
#    script: "./gradlew dockerPush"
